const DATA = {
  suppliers: [
    {
      id: 1,
      site: "https://www.supplier1.com",
      name: "Supplier 1",
      city: "Moscow",
      type: "Marka1",
      email: "nQ1rj@example.com",
      phone: "+7 123 456 78 90",
      date: "01.01.2022",
      state: "active",
      price: 10000,
      isBlocked: false,
    },
    {
      id: 2,
      site: "https://www.supplier1.com",
      name: "Supplier 2",
      city: "Moscow",
      type: "Marka1",
      email: "nQ1rj@example.com",
      phone: "+7 123 456 78 90",
      date: "01.01.2022",
      state: "active",
      price: 10000,
      isBlocked: false,
    },
    {
      id: 3,
      site: "https://www.supplier1.com",
      name: "Supplier 3",
      city: "Moscow",
      type: "Marka1",
      email: "nQ1rj@example.com",
      phone: "+7 123 456 78 90",
      date: "01.01.2022",
      state: "active",
      price: 10000,
      isBlocked: false,
    },
    {
      id: 4,
      site: "https://www.supplier1.com",
      name: "Supplier 4",
      city: "Moscow",
      type: "Marka1",
      email: "nQ1rj@example.com",
      phone: "+7 123 456 78 90",
      date: "01.01.2022",
      state: "active",
      price: 10000,
      isBlocked: false,
    },
    {
      id: 5,
      site: "https://www.supplier1.com",
      name: "Supplier 5",
      city: "Moscow",
      type: "Marka1",
      email: "nQ1rj@example.com",
      phone: "+7 123 456 78 90",
      date: "01.01.2022",
      state: "active",
      price: 10000,
      isBlocked: false,
    },
    {
      id: 6,
      site: "https://www.supplier1.com",
      name: "Supplier 6",
      city: "Moscow",
      type: "Marka1",
      email: "nQ1rj@example.com",
      phone: "+7 123 456 78 90",
      date: "01.01.2022",
      state: "active",
      price: 10000,
      isBlocked: false,
    },
    {
      id: 7,
      site: "https://www.supplier1.com",
      name: "Supplier 7",
      city: "Moscow",
      type: "Marka1",
      email: "nQ1rj@example.com",
      phone: "+7 123 456 78 90",
      date: "01.01.2022",
      state: "active",
      price: 10000,
      isBlocked: false,
    },
    {
      id: 8,
      site: "https://www.supplier1.com",
      name: "Supplier 8",
      city: "Moscow",
      type: "Marka1",
      email: "nQ1rj@example.com",
      phone: "+7 123 456 78 90",
      date: "01.01.2022",
      state: "active",
      price: 10000,
      isBlocked: false,
    },
    {
      id: 9,
      site: "https://www.supplier1.com",
      name: "Supplier 9",
      city: "Moscow",
      type: "Marka1",
      email: "nQ1rj@example.com",
      phone: "+7 123 456 78 90",
      date: "01.01.2022",
      state: "active",
      price: 10000,
      isBlocked: false,
    },
    {
      id: 10,
      site: "https://www.supplier1.com",
      name: "Supplier 10",
      city: "Moscow",
      type: "Marka1",
      email: "nQ1rj@example.com",
      phone: "+7 123 456 78 90",
      date: "01.01.2022",
      state: "active",
      price: 10000,
      isBlocked: false,
    },
    {
      id: 11,
      site: "https://www.supplier1.com",
      name: "Supplier 11",
      city: "Moscow",
      type: "Marka1",
      email: "nQ1rj@example.com",
      phone: "+7 123 456 78 90",
      date: "01.01.2022",
      state: "active",
      price: 10000,
      isBlocked: false,
    },
    {
      id: 12,
      site: "https://www.supplier1.com",
      name: "Supplier 12",
      city: "Moscow",
      type: "Marka1",
      email: "nQ1rj@example.com",
      phone: "+7 123 456 78 90",
      date: "01.01.2022",
      state: "active",
      price: 10000,
      isBlocked: false,
    },
  ],
};

export default DATA;
